#!/bin/bash
set -e
docker build -t "standard-input-sanitizer" docker
docker run -it --rm --cap-drop=ALL -v "$PWD:/app" -v "$PWD/docker:/app/docker:ro" --name running-standard-input-sanitizer "standard-input-sanitizer"
